spring:
  profiles:
    active: dev
  application:
    name: eshop

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:eshop/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user-token-expire: 30

logging:
  config: classpath:logback-spring.xml
