spring:
  profiles:
    active: dev
  application:
    name: eshop
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:eshop/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user-token-expire: 12

merchant-token-expire: 12

admin-account: admin

admin-password: 111

admin-token-expire: 12

logging:
  config: classpath:logback-spring.xml

