spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.66.218:3306/eshop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: huangfen123
  redis:
    host: localhost
    port: 6379
    password: 123456

picture-nginx-host: http://39.96.66.218:80/